journals={
        'ASCE_SEJ':'ASCEJournalStructuralEngineering',                             #1
        'ASCE_DCP':'ASCEJournalStructuralDesignConstructionPractice',              #2
        'ASCE_PCF':'ASCEJournalPerformanceConstructedFacilities',                  #3
        'ASCE_JCC':'ASCEJournalCompositesConstruction',                            #4
        'ACIJ_ASJ':'ACIStructuralJournal',                                         #5
        'AISC_JSE':'AISCJournalStructuralEngineering',                             #6
        'ELSE_CST':'ElsevierComputersStructures',                                  #7
        'ELSE_EST':'ElsevierEngineeringStructures',                                #8
        'ELSE_STS':'ElsevierStructuralSafety',                                     #9
        'ELSE_FEA':'ElsevierFiniteElementsAnalysisDesign',                         #10
        'ELSE_CSR':'ElsevierJournalConstructionalSteelResearch',                   #11
        'SPRI_EEV':'SpringerEarthquakeEngineeringEngineeringVibrations',           #12
        'SPRI_ISS':'SpringerInternationalJournalSteelStructures',                  #13
        'SPRI_BEE':'SpringerBulletinEarthquakeEngineering',                        #14
        'SPRI_SMO':'SpringerStructuralMultidisciplinaryOptimization',              #15
        'SPRI_MAS':'SpringerMaterialsStructures',                                  #16
        'SPRI_CME':'SpringerComputationalMechanics',                               #17
        'SAGE_EQS':'SageEarthquakeSpectra',                                        #18
        'SAGE_ASE':'SageAdvancesStructuralEngineering',                            #19
        'WILY_TSB':'WileyStructuralDesignTallSpecialBuildings',                    #20
        'WILY_EED':'WileyEarthquakeEngineeringStructuralDynamics',                 #21
        'WILY_CHM':'WileyStructuralControlHealthMonitoring',                       #22
        'WILY_NME':'WileyInternationalJournalNumericalMethodsEngineering',         #23
        'TAFR_JEE':'TaylorFrancisJournalEarthquakeEngineering',                    #24
        'TAFR_MSM':'TaylorFrancisMechanicsStructuresMaterials',                    #25
        'JSEE_SEE':'JSEEJournalSeismologyEarthquakeEngineering',                   #26
        'IABS_SSE':'IABSEJournalSeismologyEarthquakeEngineering',                  #27
        'WSCP_SSD':'WSCInternationalJournalStructuralStabilityDynamics',           #28
        'TAFR_EST':'TaFrEngineeringStructuresandTechnologies',                     #29
        'TAFR_ABE':'TaFrJournalAsianArchitectureBuildingEngineering',              #30
        'SPRI_WWP':'SpringerEuropeanJournalWoodProducts',                          #31
        'ELSE_CBM':'ElsevierConstructionBuildingMaterials',                        #32
        'ELSE_JBE':'ElsevierJournalBuildingEngineering',                           #33
        'INDE_MSI':'InderScienceInternationalJournalMaterialsStructuralIntegrity', #34
        'INDE_JSE':'InderScienceInternationalJournalStructuraEngineering',         #35
        'INDE_EIE':'InderScienceInternationalJournalEarthquakeImpactEngineering',  #36
        'INDE_MRI':'InderScienceInternationalJournalMasonryResearchInnovation',    #37
        'TECH_SCS':'TechnoSteelCompositeStructures',                               #38
        'TECH_SEM':'TechnoStructuralEngineeringMechanics',                         #39
        'TECH_ACC':'TechnoAdvancesConcreteConstruction',                           #40
        'TECH_COC':'TechnoComputersConcrete',                                      #41
        'TECH_EQS':'TechnoEarthquakesStructures',                                  #42
        'TECH_SSS':'TechnoSmartStructuresSystems',                                 #43
        'TECH_WST':'TechnoWindStructures',                                         #44
        'CASP_CCE':'CASPCanadianJournalCivilEngineering',                          #45
        'NZEE_BEE':'NZSEEBulletinEarthquakeEngineering',                           #46
        }

